eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      # 유레카 서버가 어디에 있는지를 위치 정보를 여기다가 명시해 둔 것이다.
      defaultZone: http://${EUREKA_SERVER_URL}:8761/eureka/

server:
  port: 8080
  tomcat:
    # 최대 스레드 개수를 10개 이내로 제한 (기본값 200)
    max-threads: 10
    # 최소 스레드 개수를 1~2개로 제한
    min-spare-threads: 2


spring:
  jackson:
    time-zone: Asia/Seoul
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:9200
    connection-timeout: 10s
    socket-timeout: 30s
  datasource:
    # MySQL 드라이버 지정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 도커 컨테이너로 3306 포트로 접속할 수 있도록 띄어놓은 db와 연결
    URL: jdbc:mysql://${DB_HOST}:3306/Glemoa
    username: ${DB_USERNAME} # 환경 변수로 변경
    password: ${DB_PASSWORD} # 환경 변수로 변경
    hikari:
      # 최대 커넥션 개수를 5개 이내로 제한 (기본값 10)
      maximum-pool-size: 5
      # 최소 유휴 커넥션 개수를 2개 이내로 제한
      minimum-idle: 2
  jpa:
    # 데이터 베이스 플랫폼에는 MySQL DB를 사용할 것이기 때문에 이렇게 설정
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

logging:
  config: classpath:logback-prod.xml
  level:
    # 1. 모든 외부 라이브러리 및 기본 동작은 INFO 레벨로 설정
    root: WARN
    # 2. Glemoa Reader 서비스의 핵심 로직만 DEBUG 레벨로 설정
    hyunsub.glemoareader: INFO